// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQNJB2lY8SL-TfuG_-UCGIgFJI1cF8xs',
    appId: '1:588480893866:web:c9d96403c67e28161091d3',
    messagingSenderId: '588480893866',
    projectId: 'terasight-3d790',
    authDomain: 'terasight-3d790.firebaseapp.com',
    storageBucket: 'terasight-3d790.firebasestorage.app',
    measurementId: 'G-KEW1GMPWDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkVvVzs0qq-NNjKi5EYsA6z_W24yDGEig',
    appId: '1:588480893866:android:320ff5a44bc5ba171091d3',
    messagingSenderId: '588480893866',
    projectId: 'terasight-3d790',
    storageBucket: 'terasight-3d790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_EIBfSrKj_3732XhFoF1CRIoAgVwhGM',
    appId: '1:588480893866:ios:4530487b1d58ac8a1091d3',
    messagingSenderId: '588480893866',
    projectId: 'terasight-3d790',
    storageBucket: 'terasight-3d790.firebasestorage.app',
    iosClientId: '588480893866-ith8g4142updafbdu8ji1p0mg7vcmcgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmdcFogSafeHaulage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj_EIBfSrKj_3732XhFoF1CRIoAgVwhGM',
    appId: '1:588480893866:ios:4530487b1d58ac8a1091d3',
    messagingSenderId: '588480893866',
    projectId: 'terasight-3d790',
    storageBucket: 'terasight-3d790.firebasestorage.app',
    iosClientId: '588480893866-ith8g4142updafbdu8ji1p0mg7vcmcgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmdcFogSafeHaulage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUQNJB2lY8SL-TfuG_-UCGIgFJI1cF8xs',
    appId: '1:588480893866:web:33ee337efc0e369e1091d3',
    messagingSenderId: '588480893866',
    projectId: 'terasight-3d790',
    authDomain: 'terasight-3d790.firebaseapp.com',
    storageBucket: 'terasight-3d790.firebasestorage.app',
    measurementId: 'G-1065Y7PV98',
  );
}
