// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxS73TQJvr4qtNXUgE0r-KomesI2vDOc',
    appId: '1:1045991871906:web:db88aa032689b072840efb',
    messagingSenderId: '1045991871906',
    projectId: 'divyapath-7bd35',
    authDomain: 'divyapath-7bd35.firebaseapp.com',
    storageBucket: 'divyapath-7bd35.firebasestorage.app',
    measurementId: 'G-HJ4VS6YRSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDKAtX2ACrne5tD2AjyfRof9dVbltF1E',
    appId: '1:1045991871906:android:b22cee483669bc56840efb',
    messagingSenderId: '1045991871906',
    projectId: 'divyapath-7bd35',
    storageBucket: 'divyapath-7bd35.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDR1UaJaSmHNVzkDtqtUm-eWD6uXSeEKQ',
    appId: '1:1045991871906:ios:09d10524d556a6b0840efb',
    messagingSenderId: '1045991871906',
    projectId: 'divyapath-7bd35',
    storageBucket: 'divyapath-7bd35.firebasestorage.app',
    iosBundleId: 'com.example.nmdcFogSafeHaulage',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDR1UaJaSmHNVzkDtqtUm-eWD6uXSeEKQ',
    appId: '1:1045991871906:ios:09d10524d556a6b0840efb',
    messagingSenderId: '1045991871906',
    projectId: 'divyapath-7bd35',
    storageBucket: 'divyapath-7bd35.firebasestorage.app',
    iosBundleId: 'com.example.nmdcFogSafeHaulage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqxS73TQJvr4qtNXUgE0r-KomesI2vDOc',
    appId: '1:1045991871906:web:a6f3b5e5642697a4840efb',
    messagingSenderId: '1045991871906',
    projectId: 'divyapath-7bd35',
    authDomain: 'divyapath-7bd35.firebaseapp.com',
    storageBucket: 'divyapath-7bd35.firebasestorage.app',
    measurementId: 'G-C01YPJVGB3',
  );
}
